import {createContext,useContext,useMemo,useState,useEffect} from 'react';
import initial from '../data/chatData.json';import {loadState,saveState} from '../utils/storage';import {uid} from '../utils/messageUtils';import {nowLabel} from '../utils/dateUtils';import {generateReply} from '../utils/replyEngine';
const C=createContext();
export function ChatProvider({children}){
 const [users]=useState(initial.users); const [conversations,setConversations]=useState(()=>loadState('baatchet-conversations',initial.conversations)); const [messages,setMessages]=useState(()=>loadState('baatchet-messages',initial.messages)); const [selected,setSelected]=useState(null); const [typing,setTyping]=useState(false); const [toast,setToast]=useState(''); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('all'); const [detailsOpen,setDetailsOpen]=useState(true); const [profile,setProfile]=useState(()=>loadState('baatchet-profile',{name:'Ankit',about:'Connect. Chat. Share. Repeat.',status:'Online',avatar:'https://i.pravatar.cc/150?img=68'}));
 useEffect(()=>{saveState('baatchet-conversations',conversations)},[conversations]);useEffect(()=>{saveState('baatchet-messages',messages)},[messages]);useEffect(()=>{saveState('baatchet-profile',profile)},[profile]);
 const userById=id=>users.find(u=>u.id===id); const selectedConv=conversations.find(c=>c.id===selected); const selectedUser=selectedConv?userById(selectedConv.userId):null;
 const visible=useMemo(()=>conversations.filter(c=>{const u=userById(c.userId);if(filter==='archived'&&!c.archived)return false;if(filter!=='archived'&&c.archived)return false;if(filter==='unread'&&!c.unread)return false;if(filter==='favorites'&&!c.favorite)return false;if(filter==='groups'&&!u?.isGroup)return false;const text=(u?.name+' '+(messages[c.id]?.at(-1)?.text||'')).toLowerCase();return !query||text.includes(query.toLowerCase())}).sort((a,b)=>Number(b.pinned)-Number(a.pinned)),[conversations,filter,query,messages]);
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2600)};
 const select=id=>{setSelected(id);setDetailsOpen(window.innerWidth>=1100);setConversations(cs=>cs.map(c=>c.id===id?{...c,unread:0}:c))};
 const send=async(text,{replyTo=null,type='text',meta=null}={})=>{if(!selected||!text?.trim())return;const msg={id:uid(),sender:'me',text:text.trim(),time:nowLabel(),status:'sent',starred:false,pinned:false,replyTo,type,meta};setMessages(m=>({...m,[selected]:[...(m[selected]||[]),msg]}));setConversations(cs=>cs.map(c=>c.id===selected?{...c,unread:0}:c));setTyping(true);setTimeout(()=>{const reply=generateReply(text,initial.responses);setMessages(m=>({...m,[selected]:[...(m[selected]||[]),{id:uid(),sender:'them',text:reply,time:nowLabel(),status:'read',starred:false,pinned:false}]}));setTyping(false);notify(`New message from ${selectedUser?.name||'BaatCheet'}`)},1100+Math.random()*900)};
 const updateMessage=(id,patch)=>setMessages(m=>({...m,[selected]:(m[selected]||[]).map(x=>x.id===id?{...x,...patch}:x)}));
 const deleteMessage=id=>updateMessage(id,{text:'This message was deleted',deleted:true});
 const toggleReaction=(id,emoji)=>setMessages(m=>({...m,[selected]:(m[selected]||[]).map(x=>x.id===id?{...x,reactions:{...(x.reactions||{}),[emoji]:((x.reactions||{})[emoji]||0)?0:1}}:x)}));
 const toggleConversation=(key)=>{if(!selected)return;setConversations(cs=>cs.map(c=>c.id===selected?{...c,[key]:!c[key]}:c))};
 const toggleStar=id=>updateMessage(id,{starred:!(messages[selected]||[]).find(x=>x.id===id)?.starred});const togglePin=id=>updateMessage(id,{pinned:!(messages[selected]||[]).find(x=>x.id===id)?.pinned});
 const archive=id=>setConversations(cs=>cs.map(c=>c.id===id?{...c,archived:!c.archived}:c));
 const value={users,userById,conversations,messages,selected,selectedUser,selectedConv,visible,typing,toast,query,setQuery,filter,setFilter,detailsOpen,setDetailsOpen,profile,setProfile,select,setSelected,send,updateMessage,deleteMessage,toggleReaction,toggleConversation,toggleStar,togglePin,archive,notify};return <C.Provider value={value}>{children}</C.Provider>;
}export const useChat=()=>useContext(C);
